sudo: true
dist: trusty
services:
  - docker
language: python
python:
  - '3.5'
before_install:
  - "pip install 'lander>=0.1.0,<0.2'"
script:
  # Compile PDF using containerized lsst-texmf
  - "docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'"
after_success:
  # Deploy website. See https://github.com/lsst-sqre/lander for CLI options
  - "lander --pdf LDM-592.pdf --upload --lsstdoc LDM-592.tex --env=travis --ltd-product $PRODUCT
env:
  global:
    - PRODUCT="ldm-592"
    # LSST the Docs credentials
    - secure: "nTy4ce1IfMl5+zv0hszQRuKr5kSLz6E9LnS0Sxu2hJKO1QSTX6eQSTUOcpyNolhQL++0Py4UEO7TT5KkdSQCG14hpMUOLIF1xJjhs5gDlU1x9KrhdLQusSnnK/d3Fp4kHzsmenIIYHzd9tlgGdlMMz5q606DbEPNH3epkq4tyC0kOeDdFqf1dlMueCdL3NWX3Lp7WIjvzHRlVJd3kWn+5CJKzAxNMmv0bxgUHW9FLz/t9f+Q0zuegZlzAXkrKNQgUVfyxpNbk7ROFABXumGuT+z9nrRQocqF4oOp9MnWgBrNI76JOK1rduNhyQzAMJkHIKZ2r0t29LJcYIUPmmShyOIIW1jXSRrV4CE2fXKU6FH0VGA4M4tbhFbtgDGukG+u3mDmsjunH1eM9CSSLDmt9v9DPMvxIQj328ikOSdkA48re9qYIRoNointWEic8Ox8vSVE5VssrPjyiBuUVSRetfknE/Mr/oPVv4CCUIlsWvI5N7ZPhfT8P4A0eKOytk2McakrVlXCopboCZVVNzluMxiXKdtGNWEkfII73qHQtOrM1+gqP1+vprDw0ERYpUdpfSAllSWCLl+TfS8iLenQP7lHsPtkHaHE+OeOqy6hI3rX9qYxSZLO+l8rlPPMvm0oGRW2MbLkyL7uuHKTjMeBH3HeB93Y5R+ijXkWod0CvBc="
    - secure: "r7/Qno/WvoYqO5tUN6RaeUoFNqL5a9v+uX4OJIXK6ElEE7rpD8rgRMV5rlrmHZKQ1m0tiae3n7dJugLZ4QsY70UmGlxpE3x2cLW6WFWLpQx2tSjJGTLeNEF9kwwArsEACcmDp4T5AG5gr2Rt7ZiZpFimS4HqiqeWZTU5PfBoykNxtFjEC4vqgVXXl+iGTfmuNFy73c9QQdwFVmud0+EpkaRqwIKebimFd1p+gslY0a1DNbQ0ryzjY+n6QWnHHtQlLLmPw5F/drAjtMbuW5CJ9j+SPeU6rnxLSyd4eC4rN9gk42STJHEw/HrpOZdpOYjjA3j5WGLYoo3LuDpPIHhv1d3vpSvZSx4+2Z/KFdHRXCxIs9QucL2kGyk+iwxk0dftUCfDpS4bkuoVj2Ha8U7Q4pH7aM/YtJvJaQOB2K1h1Q32OutrN4JSXwmPDH5Pz9TTvdZDGLI1yHmC5E8nmv3+PCnfNmnI2sqnyCUWN7WuakjKsTp2P14il6VWevsrAqX7A2k8dt3ikLIu1OUykUXvktiGB6tZPL2/BtbR97Zu0ZWxULU++2wgFoytNFxaU1m/VHwInT3aH3deN1wn7LM1/a7UAkVbkKsr+qpaV2u2ZXSm9nXHW5BZjSacOzGmKaSVAK+ICDNcvnn7zOUqYzBYo2pK/6L2YW2Mqa3gu0na3no="
